import { data } from "autoprefixer";
import Head from "next/head";
import styles from "../../styles/Home.module.css";
import About from "../components/about.component";
import ShortenForm from "../components/shorten-form";
import Uses from "../components/uses.component";
import { useState } from "react";

export default function Home() {
  const [url, setUrl] = useState();
  const [showResult, setShowResult] = useState(false);

  const handleData = (data) => {
    setUrl(data);
    setShowResult(true);
  };
  const [copySuccess, setCopySuccess] = useState("Click here to copy");

  // your function to copy here

  const copyToClipBoard = async (copyMe) => {
    try {
      await navigator.clipboard.writeText(copyMe);
      setCopySuccess("Copied!");
    } catch (err) {
      setCopySuccess("Failed to copy!");
    }
  };

  return (
    <div className="text-center w-3/5 mx-auto sm:w-11/12">
      <Head>
        <title>TeenyUrl</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="my-8">
        <h2 className="text-primary text-6xl font-bold">Teeny URL</h2>
      </header>
      <section className="bg-white shadow-sm py-6 sm:px-4">
        <h4 className="text-4xl text-secondary font-bold mb-2">
          Paste the URL to shorten
        </h4>
        <ShortenForm onData={handleData} />
        {showResult ? (
          <div className="my-4">
            <h2 className="text-base">Shortened Url:</h2>
            <h5 id="result" className="text-secondary-dark text-xl">
              {url}
            </h5>
            <div>
              <button
                onClick={(setUrl) =>
                  copyToClipBoard(setUrl)
                }
                className="mt-4"
              >
                {copySuccess}
              </button>
            </div>

            <h6
              onClick={() => {
                window.location.reload(false);
              }}
              className="cursor-pointer underline text-base my-6 text-primary"
            >
              Make another shortened URL
            </h6>
          </div>
        ) : (
          ""
        )}

        <p className="py-4 text-base">
          TeenyUrl is a free tool to shorten a URL or reduce a link <br />
          Use our URL Shortener to create a shortened link making it easy to
          remember
        </p>
      </section>
      <About
        heading="Simple and fast URL shortener!"
        content="TeenyURL allows to reduce long links from Instagram, Facebook, YouTube, Twitter, Linked In and top sites on the Internet, just paste the long URL and click the Shorten URL button. On the next screen, copy the shortened URL and share it on websites, chat and e-mail. After shortening the URL, check how many clicks it received."
      />
      <About
        heading="Shorten, share and track"
        content="Your shortened URLs can be used in publications, documents, advertisements, blogs, forums, instant messages, and other locations. Track statistics for your business and projects by monitoring the number of hits from your URL with the click counter, you do not have to register."
      />
      <Uses />
    </div>
  );
}
