import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import About from "../components/about.component";
import Uses from "../components/uses.component";

export default function Home() {
  return (
    <div className="text-center w-3/5 mx-auto sm:w-11/12">
      <Head>
        <title>TeenyUrl</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="my-8">
        <h2 className="text-primary text-6xl font-bold">Teeny URL</h2>
      </header>
      <section className="bg-white shadow-sm py-6 sm:px-4">
        <h4 className="text-4xl text-secondary font-bold mb-2">Paste the URL to shorten</h4>
        <div className="flex mt-4 justify-center">
          <input placeholder="Paste URL" className="border h-14 px-4 w-3/5 rounded-tl-md rounded-bl-md"/>
          <button className="bg-primary-dark text-white h-14 text-lg p-4 font-bold flex items-center rounded-tr-md rounded-br-md">Shorten</button>
        </div>
        <p className="py-4 text-base">
          TeenyUrl is a free tool to shorten a URL or reduce a link <br />
          Use our URL Shortener to create a shortened link making it easy to
          remember
        </p>
      </section>
      <About
        heading="Simple and fast URL shortener!"
        content="TeenyURL allows to reduce long links from Instagram, Facebook, YouTube, Twitter, Linked In and top sites on the Internet, just paste the long URL and click the Shorten URL button. On the next screen, copy the shortened URL and share it on websites, chat and e-mail. After shortening the URL, check how many clicks it received."
      />
      <About
        heading="Shorten, share and track"
        content="Your shortened URLs can be used in publications, documents, advertisements, blogs, forums, instant messages, and other locations. Track statistics for your business and projects by monitoring the number of hits from your URL with the click counter, you do not have to register."
      />
      <Uses/>
    </div>
  );
}
